input {
  file {
    path => "/home/kali/siem-dashboard/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if "Failed password" in [message] {
    mutate { add_tag => ["failed_login"] }
  }
}

output {
  elasticsearch {
    hosts => ["https://127.0.0.1:9200"]
    user => "elastic"
    password => "elastic321"
    ssl => true
    ssl_certificate_verification => false
    index => "siem-logs"
  }

  stdout { codec => rubydebug }
}input {
  file {
    path => "/home/kali/siem-dashboard/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if "Failed password" in [message] {
    mutate { add_tag => ["failed_login"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "siem-logs"
  }
  stdout { codec => rubydebug }
}
